#!/bin/bash

##Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"


function ctrl_c (){
  echo -e "\n\n[!] Saliendo....\n"
  tput cnorm exit 1
}

## CTRL_C
trap ctrl_c INT

tput civis
echo -e "ip publica -->${redColour}$(curl -s ifconfig.me)${endColour}" 
echo -e "ip privada --> ${turquoiseColour}$(ip a | grep "ens33" | tail -n 1 | awk '{print $2}' | tr "/" " " | awk '{print $1}')${endColour}" 
echo -e "\n${greenColour}grupos a los que perteneces:${endColour} \n${grayColour}$(id)${endColour}"
echo -e "\n${yellowColour}---Listando Archivos SUID & SGUID---${endColour}"
echo -e "${purpleColour}$(find / -type f -perm -4000 1>suid 2>/dev/null)${endColour}" &
wait
echo -e "${purpleColour}Permisos SUID${endColour}"
echo -e "${purpleColour}$(cat suid | xargs ls -l)${endColour}"
echo -e "${blueColour}$(find / -type f -perm -2000 1>sguid 2>/dev/null)${endColour}" &
wait
echo -e "${blueColour}Permisos SGUID${endColour}"
echo -e "${blueColour}$(cat sguid | xargs ls -l)${endColour}"
echo -e "${grayColour}$(getcap -r / 1>capabilities 2>/dev/null)${endColour}" &
wait
echo -e "${grayColour}Capabilities${endColour}" 
echo -e "${grayColour}$(cat capabilities)${endColour}"

tput cnorm
