#!/bin/bash
#
##Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

echo -e "ip publica -->${redColour}$(curl ifconfig.me)${endColour}"
echo -e "ip privada --> ${turquoiseColour}$(ip a | grep "ens33" | tail -n 1 | awk '{print $2}' | tr "/" " " | awk '{print $1}')${endColour}"
echo -e "\n${greenColour}grupos a los que perteneces:${endColour} \n${grayColour}$(id)${endColour}"

echo -e "\n${yellowColour}---Listando Archivos SUID & SGUID---${endColour}"
echo -e "${purpleColour}$(find / -type f -perm -4000 1>suid 2>/dev/null)${endColour}"
echo -e "${blueColour}$(find / -type f -perm -2000 1>sguid 2>/dev/null)${endColour}"
echo -e "${purpleColour}Permisos SUID${endColour}\n"
echo -e "${purpleColour}$(cat suid | xargs ls -la)${endColour}\n"
echo -e "${blueColour}Permisos SGUID${endColour}\n"
echo -e "${blueColour}$(cat sguid | xargs ls -la)${endColour}\n"
